---
# Setup folders
- name: Ensure deployment Apps base path exists
  file:
    state: directory
    path: "{{ ansistrano_apps_to }}"

- name: Ensure releases folder exists
  file:
    state: directory
    path: "{{ ansistrano_releases_path }}"

- name: Ensure shared elements folder exists
  file:
    state: directory
    path: "{{ ansistrano_shared_path }}"

# Ensure shared path exists
- name: Ensure shared paths exists
  file:
    state: directory
    path: "{{ ansistrano_shared_path }}/{{ item }}"
  with_items: "{{ ansistrano_shared_paths }}"
  when: ansistrano_ensure_shared_paths_exist

# Ensure basedir shared files exists
- name: Ensure basedir shared files exists
  file:
    state: directory
    path: "{{ ansistrano_shared_path }}/{{ item | dirname }}"
  with_items: "{{ ansistrano_shared_files }}"
  when: ansistrano_ensure_basedirs_shared_files_exist